apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-assignment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-assignment
  template:
    metadata:
      labels:
        app: docker-assignment
    spec:
      containers:
      - name: docker-assignment-container  # Updated container name to use dash
        image: sonutiwari1234
        imagePullPolicy: IfNotPresent
